openapi: 3.0.0
info:
  title: Ambil Semua Data Karyawan BCA
  version: 1.0.0
tags:
  - name: Daftar API
parameters:
  - name: id_karyawan
    in: path
    description: ID karyawan yang akan diperbarui
    required: true
    type: integer
  - in: body
    name: body
    description: Data karyawan yang akan diperbarui
    required: true
    schema:
      $ref: '#/definitions/Karyawan'
responses:
  200:
    description: Data berhasil diperbarui
    schema:
      $ref: '#/definitions/Karyawan'
  404:
    description: Data tidak ditemukan